import type {
  KeywordData,
  KeywordMetrics,
  SerpResult,
  KeywordIdea,
  KeywordFolder,
  Location,
} from "./types";

export const locations: Location[] = [
  { code: "US", name: "United States" },
  { code: "UK", name: "United Kingdom" },
  { code: "CA", name: "Canada" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "AU", name: "Australia" },
  { code: "JP", name: "Japan" },
  { code: "BR", name: "Brazil" },
];

export const exampleKeywords = [
  "seo tools",
  "keyword research",
  "backlink checker",
  "content marketing",
  "rank tracker",
];

const generateTrend = (): number[] => {
  const base = Math.random() * 50000 + 1000;
  return Array.from({ length: 12 }, (_, i) => {
    const seasonal = Math.sin((i / 12) * Math.PI * 2) * 0.2;
    const trend = (i / 12) * 0.3;
    return Math.floor(base * (1 + seasonal + trend * (Math.random() - 0.5)));
  });
};

export const mockKeywords: KeywordData[] = [
  {
    keyword: "seo tools",
    volume: 74000,
    kd: 82,
    cpc: 12.45,
    competition: 0.89,
    intent: "Commercial",
    trend: generateTrend(),
  },
  {
    keyword: "keyword research",
    volume: 49500,
    kd: 75,
    cpc: 9.3,
    competition: 0.85,
    intent: "Commercial",
    trend: generateTrend(),
  },
  {
    keyword: "seo audit",
    volume: 33100,
    kd: 68,
    cpc: 15.2,
    competition: 0.78,
    intent: "Commercial",
    trend: generateTrend(),
  },
  {
    keyword: "backlink checker",
    volume: 27100,
    kd: 71,
    cpc: 11.8,
    competition: 0.82,
    intent: "Commercial",
    trend: generateTrend(),
  },
  {
    keyword: "rank tracker",
    volume: 22200,
    kd: 65,
    cpc: 13.4,
    competition: 0.76,
    intent: "Commercial",
    trend: generateTrend(),
  },
  {
    keyword: "what is seo",
    volume: 201000,
    kd: 45,
    cpc: 3.2,
    competition: 0.42,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "how to do seo",
    volume: 18100,
    kd: 52,
    cpc: 4.5,
    competition: 0.55,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "seo best practices",
    volume: 14800,
    kd: 58,
    cpc: 6.7,
    competition: 0.63,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "on page seo",
    volume: 12100,
    kd: 61,
    cpc: 7.9,
    competition: 0.68,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "technical seo",
    volume: 9900,
    kd: 64,
    cpc: 8.5,
    competition: 0.71,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "semrush",
    volume: 823000,
    kd: 92,
    cpc: 18.5,
    competition: 0.95,
    intent: "Navigational",
    trend: generateTrend(),
  },
  {
    keyword: "ahrefs",
    volume: 673000,
    kd: 90,
    cpc: 17.2,
    competition: 0.94,
    intent: "Navigational",
    trend: generateTrend(),
  },
  {
    keyword: "moz",
    volume: 301000,
    kd: 88,
    cpc: 14.8,
    competition: 0.91,
    intent: "Navigational",
    trend: generateTrend(),
  },
  {
    keyword: "screaming frog",
    volume: 110000,
    kd: 73,
    cpc: 10.3,
    competition: 0.79,
    intent: "Navigational",
    trend: generateTrend(),
  },
  {
    keyword: "buy seo software",
    volume: 8100,
    kd: 78,
    cpc: 22.4,
    competition: 0.88,
    intent: "Transactional",
    trend: generateTrend(),
  },
  {
    keyword: "seo agency near me",
    volume: 5400,
    kd: 42,
    cpc: 28.9,
    competition: 0.72,
    intent: "Transactional",
    trend: generateTrend(),
  },
  {
    keyword: "hire seo expert",
    volume: 4400,
    kd: 48,
    cpc: 31.5,
    competition: 0.75,
    intent: "Transactional",
    trend: generateTrend(),
  },
  {
    keyword: "local seo",
    volume: 40500,
    kd: 69,
    cpc: 19.8,
    competition: 0.8,
    intent: "Commercial",
    trend: generateTrend(),
  },
  {
    keyword: "content optimization",
    volume: 6600,
    kd: 54,
    cpc: 7.3,
    competition: 0.59,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "link building",
    volume: 22200,
    kd: 72,
    cpc: 13.9,
    competition: 0.83,
    intent: "Commercial",
    trend: generateTrend(),
  },
  {
    keyword: "keyword difficulty",
    volume: 8100,
    kd: 58,
    cpc: 5.4,
    competition: 0.61,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "serp analysis",
    volume: 5400,
    kd: 55,
    cpc: 6.2,
    competition: 0.6,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "competitor analysis",
    volume: 18100,
    kd: 66,
    cpc: 11.2,
    competition: 0.74,
    intent: "Commercial",
    trend: generateTrend(),
  },
  {
    keyword: "google keyword planner",
    volume: 135000,
    kd: 70,
    cpc: 8.8,
    competition: 0.77,
    intent: "Navigational",
    trend: generateTrend(),
  },
  {
    keyword: "search volume",
    volume: 12100,
    kd: 52,
    cpc: 4.9,
    competition: 0.56,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "long tail keywords",
    volume: 14800,
    kd: 49,
    cpc: 5.6,
    competition: 0.54,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "seo strategy",
    volume: 9900,
    kd: 63,
    cpc: 8.7,
    competition: 0.7,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "organic traffic",
    volume: 8100,
    kd: 57,
    cpc: 6.8,
    competition: 0.62,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "seo ranking factors",
    volume: 6600,
    kd: 60,
    cpc: 7.1,
    competition: 0.65,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "meta description",
    volume: 22200,
    kd: 44,
    cpc: 3.8,
    competition: 0.48,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "title tag",
    volume: 18100,
    kd: 46,
    cpc: 4.1,
    competition: 0.5,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "seo copywriting",
    volume: 5400,
    kd: 62,
    cpc: 9.2,
    competition: 0.69,
    intent: "Commercial",
    trend: generateTrend(),
  },
  {
    keyword: "page speed optimization",
    volume: 4400,
    kd: 56,
    cpc: 7.5,
    competition: 0.61,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "mobile seo",
    volume: 9900,
    kd: 59,
    cpc: 8.3,
    competition: 0.66,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "voice search optimization",
    volume: 3600,
    kd: 51,
    cpc: 6.4,
    competition: 0.57,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "seo content writing",
    volume: 8100,
    kd: 64,
    cpc: 10.5,
    competition: 0.71,
    intent: "Commercial",
    trend: generateTrend(),
  },
  {
    keyword: "google search console",
    volume: 246000,
    kd: 67,
    cpc: 5.9,
    competition: 0.73,
    intent: "Navigational",
    trend: generateTrend(),
  },
  {
    keyword: "sitemap xml",
    volume: 33100,
    kd: 41,
    cpc: 2.9,
    competition: 0.45,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "robots txt",
    volume: 27100,
    kd: 38,
    cpc: 2.4,
    competition: 0.41,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "canonical url",
    volume: 12100,
    kd: 47,
    cpc: 3.6,
    competition: 0.51,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "schema markup",
    volume: 14800,
    kd: 53,
    cpc: 5.8,
    competition: 0.58,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "internal linking",
    volume: 6600,
    kd: 50,
    cpc: 5.2,
    competition: 0.55,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "external links",
    volume: 4400,
    kd: 43,
    cpc: 3.5,
    competition: 0.47,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "anchor text",
    volume: 8100,
    kd: 48,
    cpc: 4.3,
    competition: 0.52,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "domain authority",
    volume: 40500,
    kd: 74,
    cpc: 12.1,
    competition: 0.81,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "page authority",
    volume: 18100,
    kd: 67,
    cpc: 9.6,
    competition: 0.73,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "seo metrics",
    volume: 5400,
    kd: 61,
    cpc: 8.2,
    competition: 0.67,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "google algorithm updates",
    volume: 9900,
    kd: 65,
    cpc: 6.5,
    competition: 0.72,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "core web vitals",
    volume: 22200,
    kd: 56,
    cpc: 5.7,
    competition: 0.6,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "ecommerce seo",
    volume: 12100,
    kd: 70,
    cpc: 16.4,
    competition: 0.78,
    intent: "Commercial",
    trend: generateTrend(),
  },
  {
    keyword: "youtube seo",
    volume: 27100,
    kd: 62,
    cpc: 7.8,
    competition: 0.68,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "image seo",
    volume: 6600,
    kd: 45,
    cpc: 4.0,
    competition: 0.49,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "video seo",
    volume: 5400,
    kd: 57,
    cpc: 7.2,
    competition: 0.62,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "seo for beginners",
    volume: 14800,
    kd: 54,
    cpc: 5.1,
    competition: 0.59,
    intent: "Informational",
    trend: generateTrend(),
  },
  {
    keyword: "advanced seo techniques",
    volume: 3600,
    kd: 66,
    cpc: 9.8,
    competition: 0.73,
    intent: "Informational",
    trend: generateTrend(),
  },
];

export const getKeywordMetrics = (keyword: string): KeywordMetrics => {
  const baseData = mockKeywords.find((k) => k.keyword === keyword) || mockKeywords[0];

  return {
    ...baseData,
    globalVolume: [
      { country: "United States", volume: Math.floor(baseData.volume * 0.45) },
      { country: "United Kingdom", volume: Math.floor(baseData.volume * 0.15) },
      { country: "Canada", volume: Math.floor(baseData.volume * 0.1) },
      { country: "Australia", volume: Math.floor(baseData.volume * 0.08) },
      { country: "Germany", volume: Math.floor(baseData.volume * 0.07) },
      { country: "France", volume: Math.floor(baseData.volume * 0.06) },
      { country: "India", volume: Math.floor(baseData.volume * 0.05) },
      { country: "Brazil", volume: Math.floor(baseData.volume * 0.04) },
    ],
  };
};

export const getSerpResults = (keyword: string): SerpResult[] => {
  const domains = [
    "moz.com",
    "ahrefs.com",
    "semrush.com",
    "searchenginejournal.com",
    "neilpatel.com",
    "backlinko.com",
    "hubspot.com",
    "wordstream.com",
    "searchengineland.com",
    "contentmarketinginstitute.com",
  ];

  return Array.from({ length: 10 }, (_, i) => ({
    position: i + 1,
    url: `https://${domains[i]}/blog/${keyword.replace(/\s+/g, "-")}`,
    domain: domains[i],
    title: `${keyword.charAt(0).toUpperCase() + keyword.slice(1)} - Complete Guide ${i + 1}`,
  }));
};

export const getKeywordIdeas = (keyword: string): KeywordIdea[] => {
  const variations: KeywordIdea[] = [
    { keyword: `${keyword} tool`, volume: 12100, kd: 68, type: "variation" },
    { keyword: `${keyword} software`, volume: 9900, kd: 72, type: "variation" },
    { keyword: `${keyword} free`, volume: 18100, kd: 54, type: "variation" },
    { keyword: `best ${keyword}`, volume: 8100, kd: 65, type: "variation" },
    { keyword: `${keyword} online`, volume: 6600, kd: 48, type: "variation" },
    { keyword: `${keyword} guide`, volume: 5400, kd: 52, type: "variation" },
    { keyword: `${keyword} tips`, volume: 4400, kd: 46, type: "variation" },
    { keyword: `${keyword} for beginners`, volume: 3600, kd: 44, type: "variation" },
  ];

  const questions: KeywordIdea[] = [
    { keyword: `what is ${keyword}`, volume: 14800, kd: 42, type: "question" },
    { keyword: `how to use ${keyword}`, volume: 8100, kd: 48, type: "question" },
    { keyword: `why is ${keyword} important`, volume: 5400, kd: 45, type: "question" },
    { keyword: `when to use ${keyword}`, volume: 2900, kd: 38, type: "question" },
    { keyword: `how does ${keyword} work`, volume: 6600, kd: 50, type: "question" },
    { keyword: `which ${keyword} is best`, volume: 4400, kd: 56, type: "question" },
    { keyword: `where to find ${keyword}`, volume: 2400, kd: 41, type: "question" },
  ];

  return [...variations, ...questions];
};

export const mockFolders: KeywordFolder[] = [
  {
    id: "1",
    name: "E-commerce Keywords",
    keywords: mockKeywords.slice(0, 8),
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Blog Content Ideas",
    keywords: mockKeywords.slice(8, 15),
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    name: "Competitor Keywords",
    keywords: mockKeywords.slice(15, 22),
    createdAt: new Date("2024-01-25"),
  },
];
